# Generated by Django 6.0.4 on 2026-04-23 07:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("ai_generated", "AI Generated"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Learning Path",
                "verbose_name_plural": "Learning Paths",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Relative importance of the knowledge point on a 0.0-1.0 scale.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prerequisite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_points",
                        to="learning.knowledgepoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Point",
                "verbose_name_plural": "Knowledge Points",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("auditory", "Auditory"),
                            ("reading_writing", "Reading/Writing"),
                            ("kinesthetic", "Kinesthetic"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=32,
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learner",
                "verbose_name_plural": "Learners",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="LearningContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("article", "Article"),
                            ("quiz", "Quiz"),
                            ("audio", "Audio"),
                            ("interactive", "Interactive"),
                        ],
                        default="article",
                        max_length=24,
                    ),
                ),
                ("content_url", models.URLField(max_length=500)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Estimated duration in minutes.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_contents",
                        to="learning.knowledgepoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Content",
                "verbose_name_plural": "Learning Contents",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="LearningAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "total_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_assessments",
                        to="learning.learningpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Assessment",
                "verbose_name_plural": "Learning Assessments",
                "ordering": ["learning_path__name", "title"],
            },
        ),
        migrations.CreateModel(
            name="LearningRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_records",
                        to="learning.learner",
                    ),
                ),
                (
                    "learning_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_records",
                        to="learning.learningcontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Record",
                "verbose_name_plural": "Learning Records",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PathNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="path_nodes",
                        to="learning.knowledgepoint",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_nodes",
                        to="learning.learningpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Path Node",
                "verbose_name_plural": "Path Nodes",
                "ordering": ["learning_path__name", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_results",
                        to="learning.learner",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_results",
                        to="learning.learningassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Result",
                "verbose_name_plural": "Assessment Results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["learner", "created_at"],
                        name="learning_as_learner_4b5e10_idx",
                    ),
                    models.Index(
                        fields=["assessment", "created_at"],
                        name="learning_as_assessm_8efc18_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="learningcontent",
            constraint=models.UniqueConstraint(
                fields=("knowledge_point", "title"),
                name="unique_content_title_per_knowledge_point",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningassessment",
            constraint=models.UniqueConstraint(
                fields=("learning_path", "title"),
                name="unique_assessment_title_per_learning_path",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningrecord",
            constraint=models.UniqueConstraint(
                fields=("learner", "learning_content"),
                name="unique_learning_record_per_learner_and_content",
            ),
        ),
        migrations.AddConstraint(
            model_name="pathnode",
            constraint=models.UniqueConstraint(
                fields=("learning_path", "sort_order"),
                name="unique_path_node_order_per_path",
            ),
        ),
        migrations.AddConstraint(
            model_name="pathnode",
            constraint=models.UniqueConstraint(
                fields=("learning_path", "knowledge_point"),
                name="unique_knowledge_point_per_learning_path",
            ),
        ),
    ]
